% MATLAB Editor Run Commands
% @version 4
% It is recommended that you do not edit this file directly, but use the
% Run button. Changes made to comments that exist outside of a
% configuration will not be saved.

%% @name minimize
%  @associatedFile /MATLAB Drive/minimize.m
%  @mostRecentlyActioned true
%  @uniqueId A6FC5DD4

minimize

